stages:
  - check_code
  - check_merge
  - check_package
  - release
  - build_binary
  - packaging
  - create_manifest
  - create_tar
  - docs
  - deploy

variables:
  CREATE_DEB: "false"
  CREATE_IMAGE: "true"
  CREATE_RPM: "false"
  ARCH: "amd64"  
  BUILD_ARCH: "amd64"
  GITLAB_ADVANCED_SAST_ENABLED: "true"
  
include:
  - project: 'devops/ci/semci'
    ref: master
    file:
      - '.gitlab-ci.yml'

deploy:
  stage: deploy
  script: 
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - cd /opt/monitoring/impulse && echo "SEMVER=$SEMVER" > .env
    - docker compose pull && docker compose up -d 
    - docker logout
    - echo "Новая версия $SEMVER успешно задеплоена!"
  tags: 
    - grafana 

      