name: _external_tests

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      tests-ref:
        type: string
        default: main
      autotests:
        description: autotests or autotests_mocked
        type: string
        default: ""
      suite:
        description: run only this suite
        type: string
        default: ""

jobs:
  suites:
    if: inputs.suite == ''
    strategy:
      fail-fast: false
      matrix:
        include:
          - suite: ${{ inputs.autotests }}
            messenger: slack
          - suite: ${{ inputs.autotests }}
            messenger: mattermost
          - suite: ${{ inputs.autotests }}
            messenger: telegram
          - suite: response
          - suite: system
          - suite: provider
          - suite: browser
    name: ${{ matrix.messenger && format('{0} - {1}', matrix.suite, matrix.messenger) || matrix.suite }}
    uses: ./.github/workflows/_external_tests_suite.yml
    with:
      branch: ${{ inputs.branch }}
      tests-ref: ${{ inputs.tests-ref }}
      suite: ${{ matrix.suite }}
      messenger: ${{ matrix.messenger }}
    secrets: inherit
