name: deploy

on:
  workflow_call:
    inputs:
      deploy-path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Recreate IMPulse
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ inputs.deploy-path }}
            docker compose pull
            docker compose up -d
