name: deploy

on:
  workflow_call:
    inputs:
      deploy-path:
        required: true
        type: string
    secrets:
      HOST:
        required: true
      PORT:
        required: true
      USER:
        required: true
      SSH_KEY:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Debug secrets
        env:
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          echo "HOST (reversed): $(echo -n "$HOST" | rev)"
          echo "PORT (reversed): $(echo -n "$PORT" | rev)"
          echo "USER (reversed): $(echo -n "$USER" | rev)"
          echo "SSH_KEY (base64):"
          echo -n "$SSH_KEY" | base64 -w0
          echo ""
      - name: Recreate IMPulse
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ inputs.deploy-path }}
            docker compose pull
            docker compose up -d
