name: develop

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - 'develop'

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml

  build-and-push-image:
    needs: tests
    uses: ./.github/workflows/_build-and-push-image.yml

  cleanup-untagged-images:
    needs: build-and-push-image
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
    - uses: dataaxiom/ghcr-cleanup-action@d52806a0dc70b430571a37da1fde39733ffd640f
      with:
        dry-run: false

  deploy:
    needs: build-and-push-image
    uses: ./.github/workflows/_deploy.yml
    with:
      deploy-path: /opt/impulse/dev
    secrets: inherit
