name: develop

concurrency:
  group: ${{ github.ref }}

on:
  push:
    branches:
    - 'develop'

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml

  build-and-push-image:
    needs: tests
    uses: ./.github/workflows/_build-and-push-image.yml

  cleanup-untagged-images:
    needs: build-and-push-image
    uses: ./.github/workflows/_cleanup-untagged-images.yml

  autotests:
    needs: build-and-push-image
    uses: ./.github/workflows/_autotests.yml
    with:
      branch: ${{ github.ref_name }}
      runs-on: self-hosted
    secrets: inherit

  deploy:
    needs: build-and-push-image #!
    uses: ./.github/workflows/_deploy.yml
    with:
      deploy-path: /opt/impulse/dev
    secrets: inherit
