name: "[m] autotests"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: false
        type: number
      branch:
        required: false
        type: string

jobs:
  autotests:
    uses: ./.github/workflows/_autotests.yml
    with:
      branch: ${{ inputs.branch || format('pr-{0}', inputs.pr_number) }}
      runs-on: self-hosted
    secrets: inherit
