name: "[m] migration"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: false
        type: number
      branch:
        required: false
        type: string

jobs:
  migration:
    uses: ./.github/workflows/_migration.yml
    with:
      branch: ${{ inputs.branch || format('pr-{0}', inputs.pr_number) }}
      deploy-path: /opt/impulse/prod
    secrets: inherit
