name: "[m] tests"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        required: false
        type: number
      suite:
        required: true
        type: choice
        options:
          - response
          - system
          - provider
          - browser
          - autotests_mocked
          - autotests

jobs:
  tests:
    uses: ./.github/workflows/_external_tests.yml
    with:
      branch: ${{ format('pr-{0}', inputs.pr_number) }}
      suites: ${{ format('["{0}"]', inputs.suite) }}
    secrets: inherit
