name: master

concurrency:
  group: ${{ github.ref }}

on:
  push:
    branches:
    - 'master'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    uses: ./.github/workflows/_build-and-push-image.yml

  deploy:
    needs: build-and-push-image
    uses: ./.github/workflows/_deploy.yml
    with:
      deploy-path: /opt/impulse/prod
    secrets: inherit
