name: tags

concurrency:
  group: ${{ github.ref }}

on:
  push:
    tags:
    - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-image:
    uses: ./.github/workflows/_build-and-push-image.yml

  notify:
    needs: build-and-push-image
    uses: ./.github/workflows/_notify.yml
    secrets: inherit
